<?php

namespace Tests\Feature\Repositories;

use App\Models\CashRegister;
use App\Repositories\CashRegisterRepository;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * Class CashRegisterRepositoryTest
 * @package Tests\Feature\Repositories
 */
class CashRegisterRepositoryTest extends TestCase
{
    /**
     * @var CashRegisterRepository
     */
    protected $cashRegisterRepository;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->cashRegisterRepository = new CashRegisterRepository(new CashRegister());
    }

    /**
     * This function test register data in table cash_register
     *
     * @test
     */
    public function createCashRegisterInstance()
    {
        $cashRegisterFactory = factory(CashRegister::class)->make()->toArray();
        $response = $this->cashRegisterRepository->create($cashRegisterFactory);

        $this->assertInstanceOf(CashRegister::class, $response);
        $this->assertDatabaseHas('cash_register', $cashRegisterFactory);
    }

    /**
     * This function test PDOException data in table cash_register
     *
     * @test
     */
    public function createCashRegisterException()
    {
        $this->expectException(\PDOException::class);
        $this->cashRegisterRepository->create([]);
    }
}
